;-----------------------------------------------------------------------------------------

; Fonte Provisoria

;-----------------------------------------------------------------------------------------


;======================== O B S E R V A C A O ============================================
;Fonte provisoria feita por uma matrix (8,16) xy

;------------------------------------------------------------------------------------------

Font1_Table:

;0x0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x1
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x2
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x3
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x4
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x5
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x6
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x7
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x8
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x9
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xa
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xb
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xc
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xd
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xe
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xf
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x10
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x11
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x12
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x13
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x14
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x15
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x16
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x17
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x18
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x19
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x1a
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x1b
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x1c
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x1d
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x1e
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x1f
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x20:
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x21:
db 0x00
db 0x00
db 0x00
db 0x00
db 0x18
db 0x3c
db 0x3c
db 0x18
db 0x18
db 0x00
db 0x18
db 0x00
db 0x00
db 0x00
db 0x00
db 0x00

;0x22:
db 0x00
db 0x00
db 0x00
db 0x00
db 0x00
db 0x6c
db 0x6c
db 0x6c
db 0x00
db 0x00
db 0x00
db 0x00
db 0x00
db 0x00
db 0x00
db 0x00

;0x23:
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x24:
db 0
db 0
db 0
db 0
db 0x18
db 0x7e
db 0xc0
db 0x7c
db 0x06
db 0xfc
db 0x18
db 0
db 0
db 0
db 0
db 0

;0x25:
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x26:
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x27:
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x28:
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x29:
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x2a:
db 0
db 0
db 0
db 0
db 0
db 0x66
db 0x3c
db 0xff
db 0x3c
db 0x66
db 0
db 0
db 0
db 0
db 0
db 0

;0x2b:
db 0
db 0
db 0
db 0
db 0
db 0x18
db 0x18
db 0x7e
db 0x18
db 0x18
db 0
db 0
db 0
db 0
db 0
db 0

;0x2c:
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0x18
db 0x18
db 0x30
db 0
db 0
db 0
db 0

;0x2d:
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0x7e
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x2e:
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0x18
db 0x18
db 0
db 0
db 0
db 0
db 0

;0x2f:
db 0x00
db 0x00
db 0x00
db 0x00
db 0x06
db 0x0c
db 0x18
db 0x30
db 0x60
db 0xc0
db 0x80
db 0x00
db 0x00
db 0x00
db 0x00
db 0x00

;0x30:
db 0
db 0
db 0
db 0
db 0x7c
db 0xce
db 0xde
db 0xf6
db 0xe6
db 0xc6
db 0x7c
db 0x00
db 0
db 0
db 0
db 0

;0x31:
db 0
db 0
db 0
db 0
db 0x18
db 0x38
db 0x18
db 0x18
db 0x18
db 0x18
db 0x7e
db 0
db 0
db 0
db 0
db 0

;0x32:
db 0
db 0
db 0
db 0
db 0x78
db 0xcc
db 0x0c
db 0x38
db 0x60
db 0xcc
db 0xfc
db 0x00
db 0
db 0
db 0
db 0

;0x33:
db 0
db 0
db 0
db 0
db 0x78
db 0xcc
db 0x0c
db 0x38
db 0x0c
db 0xcc
db 0x78
db 0x00
db 0
db 0
db 0
db 0

;0x34:
db 0
db 0
db 0
db 0
db 0x1c
db 0x3c
db 0x6c
db 0xcc
db 0xfe
db 0x0c
db 0x1e
db 0x00
db 0
db 0
db 0
db 0

;0x35:
db 0
db 0
db 0
db 0
db 0xfc
db 0xc0
db 0xf8
db 0x0c
db 0x0c
db 0xcc
db 0x78
db 0x00
db 0
db 0
db 0
db 0

;0x36:
db 0
db 0
db 0
db 0
db 0x38
db 0x60
db 0xc0
db 0xf8
db 0xcc
db 0xcc
db 0x38
db 0x00
db 0
db 0
db 0
db 0

;0x37:
db 0
db 0
db 0
db 0
db 0xfc
db 0xcc
db 0x0c
db 0x18
db 0x30
db 0x30
db 0x30
db 0x00
db 0
db 0
db 0
db 0

;0x38:
db 0
db 0
db 0
db 0
db 0x7c
db 0xc6
db 0xc6
db 0x7c
db 0xc6
db 0xc6
db 0x7c
db 0x00
db 0
db 0
db 0
db 0

;0x39:
db 0
db 0
db 0
db 0
db 0x78
db 0xcc
db 0xcc
db 0x3c
db 0x0c
db 0x18
db 0x70
db 0x00
db 0
db 0
db 0
db 0

;0x3a:
db 0
db 0
db 0
db 0
db 0x00
db 0x18
db 0x18
db 0x00
db 0x00
db 0x18
db 0x18
db 0x00
db 0
db 0
db 0
db 0

;0x3b:
db 0
db 0
db 0
db 0
db 0x00
db 0x18
db 0x18
db 0x00
db 0x00
db 0x18
db 0x18
db 0x30
db 0
db 0
db 0
db 0

;0x3c:
db 0
db 0
db 0
db 0
db 0x18
db 0x30
db 0x60
db 0xc0
db 0x60
db 0x30
db 0x18
db 0x00
db 0
db 0
db 0
db 0

;0x3d:
db 0
db 0
db 0
db 0
db 0x00
db 0x00
db 0x3e
db 0x00
db 0x3e
db 0x00
db 0x00
db 0x00
db 0
db 0
db 0
db 0

;0x3e:
db 0
db 0
db 0
db 0
db 0x60
db 0x30
db 0x18
db 0x0c
db 0x18
db 0x30
db 0x60
db 0x00
db 0
db 0
db 0
db 0

;0x3f:
db 0
db 0
db 0
db 0
db 0x3c
db 0x66
db 0x0c
db 0x18
db 0x18
db 0x00
db 0x18
db 0x00
db 0
db 0
db 0
db 0

;0x40:
db 0
db 0
db 0
db 0
db 0x7c
db 0xc6
db 0xde
db 0xde
db 0xdc
db 0xc0
db 0x7c
db 0x00
db 0
db 0
db 0
db 0

;0x41:
db 0
db 0
db 0
db 0
db 0x30
db 0x78
db 0xcc
db 0xcc
db 0xfc
db 0xcc
db 0xcc
db 0x00
db 0
db 0
db 0
db 0

;0x42:
db 0
db 0
db 0
db 0
db 0xfc
db 0x66
db 0x66
db 0x7c
db 0x66
db 0x66
db 0xfc
db 0x00
db 0
db 0
db 0
db 0

;0x43:
db 0
db 0
db 0
db 0
db 0x3c
db 0x66
db 0xc0
db 0xc0
db 0xc0
db 0x66
db 0x3c
db 0x00
db 0
db 0
db 0
db 0

;0x44:
db 0
db 0
db 0
db 0
db 0xf8
db 0x6c
db 0x66
db 0x66
db 0x66
db 0x6c
db 0xf8
db 0x00
db 0
db 0
db 0
db 0

;0x45:
db 0
db 0
db 0
db 0
db 0xfe
db 0x62
db 0x68
db 0x78
db 0x68
db 0x62
db 0xfe
db 0x00
db 0
db 0
db 0
db 0

;0x46:
db 0
db 0
db 0
db 0
db 0xfe
db 0x62
db 0x68
db 0x78
db 0x68
db 0x60
db 0xf0
db 0x00
db 0
db 0
db 0
db 0

;0x47:
db 0
db 0
db 0
db 0
db 0x3c
db 0x66
db 0xc0
db 0xc0
db 0xce
db 0x66
db 0x3a
db 0x00
db 0
db 0
db 0
db 0

;0x48:
db 0
db 0
db 0
db 0
db 0xcc
db 0xcc
db 0xcc
db 0xfc
db 0xcc
db 0xcc
db 0xcc
db 0x00
db 0
db 0
db 0
db 0

;0x49:
db 0
db 0
db 0
db 0
db 0x78
db 0x30
db 0x30
db 0x30
db 0x30
db 0x30
db 0x78
db 0x00
db 0
db 0
db 0
db 0

;0x4a:
db 0
db 0
db 0
db 0
db 0x0e
db 0x0c
db 0x0c
db 0x0c
db 0xcc
db 0xcc
db 0x38
db 0x00
db 0
db 0
db 0
db 0

;0x4b:
db 0
db 0
db 0
db 0
db 0xe6
db 0x66
db 0x6c
db 0x78
db 0x6c
db 0x66
db 0xe6
db 0x00
db 0
db 0
db 0
db 0

;0x4c:
db 0
db 0
db 0
db 0
db 0xf0
db 0x60
db 0x60
db 0x60
db 0x62
db 0x66
db 0xfe
db 0x00
db 0
db 0
db 0
db 0

;0x4d:
db 0
db 0
db 0
db 0
db 0xc6
db 0xee
db 0xfe
db 0xfe
db 0xd6
db 0xc6
db 0xc6
db 0x00
db 0
db 0
db 0
db 0

;0x4e:
db 0
db 0
db 0
db 0
db 0xc6
db 0xe6
db 0xf6
db 0xd6
db 0xce
db 0xc6
db 0xc6
db 0x00
db 0
db 0
db 0
db 0

;0x4f:
db 0
db 0
db 0
db 0
db 0x38
db 0x6c
db 0xc6
db 0xc6
db 0xc6
db 0x6c
db 0x38
db 0x00
db 0
db 0
db 0
db 0

;0x50:
db 0
db 0
db 0
db 0
db 0xfc
db 0x66
db 0x66
db 0x7c
db 0x60
db 0x60
db 0xf0
db 0x00
db 0
db 0
db 0
db 0

;0x51:
db 0
db 0
db 0
db 0
db 0x7c
db 0xc6
db 0xc6
db 0xc6
db 0xd6
db 0x7c
db 0x0e
db 0x00
db 0
db 0
db 0
db 0

;0x52:
db 0
db 0
db 0
db 0
db 0xfc
db 0x66
db 0x66
db 0x7c
db 0x6c
db 0x66
db 0xe6
db 0x00
db 0
db 0
db 0
db 0

;0x53:
db 0
db 0
db 0
db 0
db 0x7c
db 0xc6
db 0xe0
db 0x78
db 0x0e
db 0xc6
db 0x7c
db 0x00
db 0
db 0
db 0
db 0

;0x54:
db 0
db 0
db 0
db 0
db 0xfc
db 0xb4
db 0x30
db 0x30
db 0x30
db 0x30
db 0x78
db 0x00
db 0
db 0
db 0
db 0

;0x55:
db 0
db 0
db 0
db 0
db 0xcc
db 0xcc
db 0xcc
db 0xcc
db 0xcc
db 0xcc
db 0xfc
db 0x00
db 0
db 0
db 0
db 0

;0x56:
db 0
db 0
db 0
db 0
db 0xcc
db 0xcc
db 0xcc
db 0xcc
db 0xcc
db 0x78
db 0x30
db 0x00
db 0
db 0
db 0
db 0

;0x57:
db 0
db 0
db 0
db 0
db 0xc6
db 0xc6
db 0xc6
db 0xc6
db 0xd6
db 0xfe
db 0x6c
db 0x00
db 0
db 0
db 0
db 0

;0x58:
db 0
db 0
db 0
db 0
db 0xc6
db 0xc6
db 0x6c
db 0x38
db 0x6c
db 0xc6
db 0xc6
db 0x00
db 0
db 0
db 0
db 0

;0x59:
db 0
db 0
db 0
db 0
db 0xcc
db 0xcc
db 0xcc
db 0x78
db 0x30
db 0x30
db 0x78
db 0x00
db 0
db 0
db 0
db 0

;0x5a:
db 0
db 0
db 0
db 0
db 0xfe
db 0xc6
db 0x8c
db 0x18
db 0x32
db 0x66
db 0xfe
db 0x00
db 0
db 0
db 0
db 0

;0x5b:
db 0
db 0
db 0
db 0
db 0x78
db 0x60
db 0x60
db 0x60
db 0x60
db 0x60
db 0x78
db 0
db 0
db 0
db 0
db 0

;0x5c:
db 0x00
db 0x00
db 0x00
db 0x00
db 0xc0
db 0x60
db 0x30
db 0x18
db 0x0c
db 0x06
db 0x02
db 0x00
db 0x00
db 0x00
db 0x00
db 0x00

;0x5d:
db 0
db 0
db 0
db 0
db 0x78
db 0x18
db 0x18
db 0x18
db 0x18
db 0x18
db 0x78
db 0
db 0
db 0
db 0
db 0

;0x5e:
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x5f:
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x60:
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x61:
db 0
db 0
db 0
db 0
db 0x00
db 0x00
db 0x38
db 0x0c
db 0x7c
db 0xcc
db 0x76
db 0x00
db 0
db 0
db 0
db 0

;0x62:
db 0
db 0
db 0
db 0
db 0xe0
db 0x60
db 0x60
db 0x7c
db 0x66
db 0x66
db 0xdc
db 0x00
db 0
db 0
db 0
db 0

;0x63:
db 0
db 0
db 0
db 0
db 0x00
db 0x00
db 0x78
db 0xcc
db 0xc0
db 0xcc
db 0x78
db 0x00
db 0
db 0
db 0
db 0

;0x64:
db 0
db 0
db 0
db 0
db 0x1c
db 0x0c
db 0x0c
db 0x7c
db 0xcc
db 0xcc
db 0x76
db 0x00
db 0
db 0
db 0
db 0

;0x65:
db 0
db 0
db 0
db 0
db 0x00
db 0x00
db 0x78
db 0xcc
db 0xfc
db 0xc0
db 0x78
db 0x00
db 0
db 0
db 0
db 0

;0x66:
db 0
db 0
db 0
db 0
db 0x38
db 0x6c
db 0x64
db 0xf0
db 0x60
db 0x60
db 0xf0
db 0x00
db 0
db 0
db 0
db 0

;0x67:
db 0
db 0
db 0
db 0
db 0
db 0
db 0x76
db 0xcc
db 0xcc
db 0x7c
db 0x0c
db 0xf8
db 0
db 0
db 0
db 0

;0x68:
db 0
db 0
db 0
db 0
db 0xe0
db 0x60
db 0x6c
db 0x76
db 0x66
db 0x66
db 0xe6
db 0x00
db 0
db 0
db 0
db 0

;0x69:
db 0
db 0
db 0
db 0
db 0x30
db 0x00
db 0x70
db 0x30
db 0x30
db 0x30
db 0x78
db 0x00
db 0
db 0
db 0
db 0

;0x6a:
db 0
db 0
db 0
db 0
db 0x0c
db 0x00
db 0x1c
db 0x0c
db 0x0c
db 0xcc
db 0xcc
db 0x78
db 0
db 0
db 0
db 0

;0x6b:
db 0
db 0
db 0
db 0
db 0xe0
db 0x60
db 0x66
db 0x6c
db 0x78
db 0x6c
db 0xe6
db 0x00
db 0
db 0
db 0
db 0

;0x6c:
db 0
db 0
db 0
db 0
db 0x70
db 0x30
db 0x30
db 0x30
db 0x30
db 0x30
db 0x78
db 0x00
db 0
db 0
db 0
db 0

;0x6d:
db 0
db 0
db 0
db 0
db 0x00
db 0x00
db 0xcc
db 0xfe
db 0xfe
db 0xd6
db 0xd6
db 0x00
db 0
db 0
db 0
db 0

;0x6e:
db 0
db 0
db 0
db 0
db 0x00
db 0x00
db 0xb8
db 0xcc
db 0xcc
db 0xcc
db 0xcc
db 0x00
db 0
db 0
db 0
db 0

;0x6f:
db 0
db 0
db 0
db 0
db 0x00
db 0x00
db 0x78
db 0xcc
db 0xcc
db 0xcc
db 0x78
db 0x00
db 0
db 0
db 0
db 0

;0x70:
db 0
db 0
db 0
db 0
db 0x00
db 0x00
db 0xdc
db 0x66
db 0x66
db 0x7c
db 0x60
db 0xf0
db 0
db 0
db 0
db 0

;0x71:
db 0
db 0
db 0
db 0
db 0x00
db 0x00
db 0x76
db 0xcc
db 0xcc
db 0x7c
db 0x0c
db 0x1e
db 0
db 0
db 0
db 0

;0x72:
db 0
db 0
db 0
db 0
db 0x00
db 0x00
db 0xdc
db 0x76
db 0x62
db 0x60
db 0xf0
db 0x00
db 0
db 0
db 0
db 0

;0x73:
db 0
db 0
db 0
db 0
db 0x00
db 0x00
db 0x7c
db 0xc0
db 0x70
db 0x1c
db 0xf8
db 0x00
db 0
db 0
db 0
db 0

;0x74:
db 0
db 0
db 0
db 0
db 0x10
db 0x30
db 0xfc
db 0x30
db 0x30
db 0x34
db 0x18
db 0x00
db 0
db 0
db 0
db 0

;0x75:
db 0
db 0
db 0
db 0
db 0x00
db 0x00
db 0xcc
db 0xcc
db 0xcc
db 0xcc
db 0x76
db 0x00
db 0
db 0
db 0
db 0

;0x76:
db 0
db 0
db 0
db 0
db 0x00
db 0x00
db 0xcc
db 0xcc
db 0xcc
db 0x78
db 0x30
db 0x00
db 0
db 0
db 0
db 0

;0x77:
db 0
db 0
db 0
db 0
db 0x00
db 0x00
db 0xc6
db 0xc6
db 0xd6
db 0xfe
db 0x6c
db 0x00
db 0
db 0
db 0
db 0

;0x78:
db 0
db 0
db 0
db 0
db 0x00
db 0x00
db 0xc6
db 0x6c
db 0x38
db 0x6c
db 0xc6
db 0x00
db 0
db 0
db 0
db 0

;0x79:
db 0
db 0
db 0
db 0
db 0x00
db 0x00
db 0xcc
db 0xcc
db 0xcc
db 0x7c
db 0x0c
db 0xf8
db 0
db 0
db 0
db 0

;0x7a:
db 0
db 0
db 0
db 0
db 0x00
db 0x00
db 0xfc
db 0x98
db 0x30
db 0x64
db 0xfc
db 0x00
db 0
db 0
db 0
db 0

;0x7b
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x7c
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x7d
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x7e
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x7f
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x80
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x81
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x82
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x83
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x84
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x85
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x86
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x87
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x88
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x89
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x8a
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x8b
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x8c
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x8d
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x8e
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x8f
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x90
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x91
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x92
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x93
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x94
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x95
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x96
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x97
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x98
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x99
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x9a
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x9b
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x9c
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x9d
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x9e
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0x9f
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xa0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xa1
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xa2
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xa3
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xa4
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xa5
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xa6
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xa7
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xa8
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xa9
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xaa
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xab
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xac
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xad
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xade
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xaf
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xb0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xb1
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xb2
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xb3
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xb4
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xb5
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xb6
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xb7
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xb8
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xb9
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xba
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xbb
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xbc
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xbd
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xbe
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xbf
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xc0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xc1
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xc2
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xc3
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xc4
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xc5
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xc6
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xc7
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xc8
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xc9
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xca
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xcb
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xcc
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xcd
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xce
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xcf
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xd0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xd1
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xd2
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xd3
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xd4
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xd5
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xd6
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xd7
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xd8
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xd9
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xda
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xdb
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xdc
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xdd
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xde
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xdf
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xe0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xe1
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xe2
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xe3
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xe4
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xe5
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xe6
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xe7
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xe8
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0


;0xe9
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xea
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xeb
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xec
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xed
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0


;0xef
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xf0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xf1
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xf2
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
;0xf3
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
;0xf4
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xf5
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xf6
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xf7
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xf8
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xf9
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xfa
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xfb
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xfc
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xfd
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xfe
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xff
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0

;0xff
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
db 0
